language: node_js
node_js: '7'
services:
  - mongodb
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
